name: Build MkDocs Executable and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs pyinstaller


    # Step 4: Build MkDocs executable with PyInstaller
    - name: Build MkDocs Executable
      run: |
        pyinstaller --clean --noconfirm --recursive-copy-metadata mkdocs \
        --collect-submodules mkdocs --collect-data mkdocs --onefile --name mkdocs-bin mkdocs_entry.py
   
     # Step 5: Upload artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mkdocs-dist
        path: /home/runner/work/stl96/stl96/dist/

          
       
    # Step 5: Deploy MkDocs site to GitHub Pages
    - name: Deploy Site
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: site
